const levels = [
 {title:'任務一：肺部補氧',story:'你是剛從身體組織回到心臟的紅血球。前往肺部，排出二氧化碳並取得氧氣。',cargo:['送出：二氧化碳','取得：氧氣'],target:'肺',icon:'🫁',fact:'肺泡外圍布滿微血管。二氧化碳由血液進入肺泡，氧氣由肺泡進入血液。',map:[
 'S...#...G','###.#.#.#','...?.#...','.#.###.#.','.#.....#.','.#.###.#.','...#...#.','!###.#...','.....#..T'],
 quizzes:[{q:'血液在肺部最主要完成哪一組交換？',o:['送出氧氣、取得二氧化碳','送出二氧化碳、取得氧氣','送出葡萄糖、取得尿素','只交換水分'],a:1,e:'肺部氣體交換使血液排出二氧化碳並獲得氧氣。'}]},
 {title:'任務二：小腸載入養分',story:'早餐消化完成了！前往小腸微血管，載入可被細胞利用的養分。',cargo:['取得：葡萄糖','取得：胺基酸'],target:'小腸',icon:'🌀',fact:'小腸內壁有許多絨毛，可增加吸收面積。葡萄糖與胺基酸會進入血液。',map:[
 'S#......T','.#.####.#','...?...#','#####.#.#','.....#...','.#.#####.','.#.....#.','.###.#.#.','G...!#...'],
 quizzes:[{q:'哪一組養分可由小腸吸收進入血液？',o:['澱粉與蛋白質大分子','葡萄糖與胺基酸','膽汁與胃酸','氧氣與二氧化碳'],a:1,e:'醣類與蛋白質需先消化成較小分子，如葡萄糖和胺基酸。'}]},
 {title:'任務三：送能量到肌肉',story:'腿部肌肉正在運動，需要細胞呼吸的原料。請把正確物質送達。',cargo:['送出：氧氣','送出：葡萄糖','帶走：二氧化碳'],target:'肌肉',icon:'💪',fact:'肌肉細胞利用氧氣與葡萄糖釋放能量，並產生二氧化碳。運動越激烈，需求通常越高。',map:[
 'S....#..G','####.#.#.','...?.#.#.','.#.###.#.','.#.....#.','.#####.#.','.....#.#.','.###.#...','!....###T'],
 quizzes:[{q:'肌肉細胞進行細胞呼吸時，最需要哪兩種原料？',o:['氧氣與葡萄糖','二氧化碳與尿素','胺基酸與尿素','水與膽汁'],a:0,e:'氧氣與葡萄糖是細胞呼吸的重要原料，可釋放細胞活動所需能量。'}]},
 {title:'任務四：肝腎廢物處理線',story:'蛋白質代謝後產生含氮廢物。先理解肝臟的處理，再前往腎臟完成清除。',cargo:['運送：尿素','調節：水與鹽類'],target:'腎臟',icon:'🫘',fact:'肝臟將有毒的氨轉為尿素；尿素隨血液抵達腎臟，被過濾後形成尿液的一部分。',map:[
 'S..#....T','.#.#.####','.#...?...','.#####.#.','.....#.#.','###..#.#.','G.#.##.#.','..#....#.','..!###...'],
 quizzes:[{q:'尿素的主要處理路徑是哪一個？',o:['肺製造，腎臟吸收','肝臟形成，腎臟排除','小腸形成，心臟排除','腦形成，肺排除'],a:1,e:'肝臟把氨轉成尿素，尿素經血液運到腎臟後排出。'}]},
 {title:'最終任務：全身循環總整理',story:'腦部需要穩定供應氧氣與葡萄糖。請完成最後運輸，並判斷正確循環觀念。',cargo:['送出：氧氣','送出：葡萄糖','帶走：二氧化碳'],target:'腦',icon:'🧠',fact:'腦細胞需要持續的氧氣與葡萄糖。血流中斷會快速影響神經細胞功能。',map:[
 'S..#....G','.#.#.##.#','.#.?....#','.#####.##','.....#...','###..###.','...#.....','.#.#####.','!#......T'],
 quizzes:[{q:'物質與組織細胞大量交換，主要發生在哪種血管？',o:['主動脈','大靜脈','微血管','冠狀動脈'],a:2,e:'微血管管壁薄、分布廣，是血液與組織細胞交換物質的主要場所。'}]}
];
const organFacts={S:['心臟','❤️','心臟收縮推動血液，是循環系統的動力來源。'],G:['知識閘門','❓','答對問題，才能證明你選擇了正確的運輸策略。'],T:['目標器官','🏁','抵達前仍要確認你攜帶的物質是否符合器官需求。'], '!':['錯誤路線','⚠️','錯誤血管可能讓運輸任務延誤，會扣分並返回上一步。'],'.':['微血管通道','🩸','血液透過血管流動；微血管是物質交換的重要場所。']};
let state={level:0,score:0,lives:3,pos:{r:0,c:0},gateDone:false,streak:0,correct:0,total:0,reviews:[],locked:false};
const $=id=>document.getElementById(id);
const screens=['introScreen','gameScreen','resultScreen'];
function showScreen(id){screens.forEach(s=>$(s).classList.toggle('active',s===id));}
function startGame(){state={level:0,score:0,lives:3,pos:{r:0,c:0},gateDone:false,streak:0,correct:0,total:0,reviews:[],locked:false};showScreen('gameScreen');loadLevel();}
function loadLevel(){const L=levels[state.level];state.gateDone=false;state.locked=false;for(let r=0;r<L.map.length;r++){const c=L.map[r].indexOf('S');if(c>=0)state.pos={r,c};}$('missionTitle').textContent=L.title;$('missionStory').textContent=L.story;$('cargoList').innerHTML=L.cargo.map(x=>`<span class="cargo-chip">${x}</span>`).join('');$('organName').textContent=L.target;$('organIcon').textContent=L.icon;$('organFact').textContent=L.fact;$('feedback').textContent='找到知識閘門並抵達目標器官。';render();updateHUD();}
function render(){const L=levels[state.level],maze=$('maze');maze.style.gridTemplateColumns=`repeat(${L.map[0].length},1fr)`;maze.innerHTML='';L.map.forEach((row,r)=>[...row].forEach((ch,c)=>{const d=document.createElement('div');d.className='cell '+(ch==='#'?'wall':'path');if(ch==='G'){d.classList.add('gate');d.textContent=state.gateDone?'✅':'❓'}if(ch==='T'){d.classList.add('target');d.textContent='🏁'}if(ch==='S')d.textContent='🚩';if(ch==='!'){d.classList.add('danger');d.textContent='⚠️'}if(r===state.pos.r&&c===state.pos.c)d.classList.add('player');maze.appendChild(d)}));$('positionLabel').textContent=`第 ${state.pos.r+1} 列，第 ${state.pos.c+1} 格`;$('gateLabel').textContent=state.gateDone?'1':'0';$('streakLabel').textContent=state.streak;}
function updateHUD(){$('levelLabel').textContent=`${state.level+1}/${levels.length}`;$('scoreLabel').textContent=state.score;$('lifeLabel').textContent='❤'.repeat(state.lives)+'♡'.repeat(3-state.lives);}
function move(dr,dc){if(state.locked)return;const L=levels[state.level],nr=state.pos.r+dr,nc=state.pos.c+dc;if(nr<0||nc<0||nr>=L.map.length||nc>=L.map[0].length||L.map[nr][nc]==='#'){bump('血管壁擋住了，換一條路！');return;}const ch=L.map[nr][nc];if(ch==='G'&&!state.gateDone){state.pos={r:nr,c:nc};render();openQuiz();return;}state.pos={r:nr,c:nc};if(ch==='!'){state.score=Math.max(0,state.score-8);state.lives--;state.streak=0;bump('走進錯誤路線：扣 8 分！');if(state.lives<=0){finish(false);return;}}else if(ch==='T'){if(!state.gateDone){bump('還沒通過知識閘門，不能完成運輸！');state.score=Math.max(0,state.score-3);}else{state.score+=20;state.reviews.push(`✅ ${L.title}：成功抵達${L.target}`);if(state.level===levels.length-1){finish(true);return;}state.level++;loadLevel();return;}}else{state.score+=1;const f=organFacts[ch]||organFacts['.'];$('organName').textContent=f[0];$('organIcon').textContent=f[1];$('organFact').textContent=f[2];}render();updateHUD();}
function bump(msg){$('feedback').textContent=msg;$('maze').classList.remove('shake');void $('maze').offsetWidth;$('maze').classList.add('shake');updateHUD();}
function openQuiz(){state.locked=true;const q=levels[state.level].quizzes[0];$('quizQuestion').textContent=q.q;$('quizOptions').innerHTML=q.o.map((o,i)=>`<label class="quiz-option"><input type="radio" name="answer" value="${i}"><span>${o}</span></label>`).join('');$('quizExplain').textContent='';$('quizExplain').className='quiz-explain';$('submitQuizBtn').classList.remove('hidden');$('continueQuizBtn').classList.add('hidden');$('quizDialog').showModal();}
function submitQuiz(){const picked=document.querySelector('input[name="answer"]:checked');if(!picked){$('quizExplain').textContent='請先選擇一個答案。';return;}const q=levels[state.level].quizzes[0],ok=Number(picked.value)===q.a;state.total++;if(ok){state.correct++;state.score+=15+state.streak*2;state.streak++;state.gateDone=true;$('quizExplain').textContent='答對了！'+q.e;$('quizExplain').className='quiz-explain good';state.reviews.push(`✅ ${q.q}`)}else{state.score=Math.max(0,state.score-5);state.streak=0;state.lives--;$('quizExplain').textContent='答案不正確。'+q.e;$('quizExplain').className='quiz-explain bad';state.reviews.push(`❌ ${q.q}`);if(state.lives<=0){$('continueQuizBtn').textContent='查看結果';}}document.querySelectorAll('input[name="answer"]').forEach(x=>x.disabled=true);$('submitQuizBtn').classList.add('hidden');$('continueQuizBtn').classList.remove('hidden');updateHUD();}
function continueQuiz(){$('quizDialog').close();state.locked=false;if(state.lives<=0){finish(false);return;}if(!state.gateDone){const L=levels[state.level];for(let r=0;r<L.map.length;r++){const c=L.map[r].indexOf('S');if(c>=0)state.pos={r,c};}$('feedback').textContent='答錯了，返回起點重新尋找閘門。';}render();}
function finish(win){showScreen('resultScreen');const accuracy=state.total?Math.round(state.correct/state.total*100):0;$('resultIcon').textContent=win?'🏆':'🩹';$('resultTitle').textContent=win?'循環運輸大師！':'任務暫停，重新整備！';$('resultText').textContent=win?'你已完成肺循環、養分吸收、組織交換與廢物排除任務。':'生命值用完了。複習器官功能後，再挑戰一次。';$('finalScore').textContent=state.score;$('accuracy').textContent=accuracy+'%';$('completedLevels').textContent=`${win?levels.length:state.level}/${levels.length}`;$('reviewList').innerHTML='<h3>學習紀錄</h3>'+state.reviews.map(x=>`<div class="review-item">${x}</div>`).join('');}
function hint(){if(state.score>=5)state.score-=5;const L=levels[state.level],target=state.gateDone?'T':'G';let best=null;for(let r=0;r<L.map.length;r++)for(let c=0;c<L.map[0].length;c++)if(L.map[r][c]===target)best={r,c};if(best){const vr=best.r-state.pos.r,vc=best.c-state.pos.c;$('feedback').textContent=`提示：${Math.abs(vr)>Math.abs(vc)?(vr>0?'往下方探索':'往上方探索'):(vc>0?'往右方探索':'往左方探索')}。`;}updateHUD();}
$('startBtn').onclick=startGame;$('playAgainBtn').onclick=startGame;$('restartLevelBtn').onclick=()=>{state.score=Math.max(0,state.score-5);loadLevel();};$('hintBtn').onclick=hint;$('openGuideBtn').onclick=()=>$('guideDialog').showModal();$('submitQuizBtn').onclick=submitQuiz;$('continueQuizBtn').onclick=continueQuiz;document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>({up:()=>move(-1,0),down:()=>move(1,0),left:()=>move(0,-1),right:()=>move(0,1)})[b.dataset.dir]());addEventListener('keydown',e=>{const k=e.key.toLowerCase(),m={arrowup:[-1,0],w:[-1,0],arrowdown:[1,0],s:[1,0],arrowleft:[0,-1],a:[0,-1],arrowright:[0,1],d:[0,1]};if(m[k]){e.preventDefault();move(...m[k]);}});
